# Generated by Django 5.0.6 on 2024-06-17 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('id_number', models.CharField(max_length=50)),
                ('legan_name', models.CharField(max_length=50)),
                ('commercial_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=5000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='document_type',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='site_category',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('short_description', models.TextField(max_length=5000, unique=True)),
                ('description', models.TextField(max_length=50000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_provider',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField()),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_provider_authorized_by', to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id_by', to='company.company')),
                ('provider_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_company_id', to='company.company')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_provider_registered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='document_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type', to='company.document_type'),
        ),
        migrations.CreateModel(
            name='company_site',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('details', models.TextField(max_length=5000, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id_company_site', to='company.company')),
                ('site_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.site_category')),
            ],
        ),
    ]
