# Generated by Django 5.0.6 on 2024-06-17 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_category',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('short_description', models.TextField(max_length=5000)),
                ('long_description', models.TextField(max_length=50000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_status',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='company_provider_service_category',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_provider_id', to='company.company_provider')),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category_id', to='services.service_category')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('service_uuid', models.UUIDField()),
                ('prospective_start_date', models.DateTimeField()),
                ('prospective_end_date', models.DateTimeField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('comments', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_company_id', to='company.company')),
                ('company_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_company_provider_id', to='company.company_provider')),
                ('company_site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_company_site_id', to='company.company_site')),
                ('contact_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_user_id', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_created_by_id', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_modified_by_id', to=settings.AUTH_USER_MODEL)),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_category_id', to='services.service_category')),
                ('service_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_status_id', to='services.service_status')),
            ],
        ),
    ]
