# Generated by Django 5.0.6 on 2024-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField()),
                ('password', models.IntegerField()),
                ('change_password', models.BooleanField()),
                ('access_type', models.CharField(max_length=200)),
                ('access_type_value', models.CharField(max_length=50)),
                ('last_accessed', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='user_registartion',
        ),
    ]
