# Generated by Django 5.0.6 on 2024-06-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_application', '0003_user_registration_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='user_permissions',
        ),
    ]
